package:
  name: ori
  version: "0.0.1"

source:
  path: ../../

requirements:
  build:
    - {{ compiler('cxx') }}
    - python==3.6.5
    - zlib
    - make
    - cmake

  run:
    - zlib
    - python==3.6.5
    - numpy==1.19.1
    - clingo==5.4.0
    - clyngor==0.3.31
    - networkx==2.5
    - pygraphviz==1.3
    - matplotlib==3.3.3